### ISSUE TITLE
Invalid description file

### ISSUE THREAD

**Issue by ogamimusashi** [kafku/RcppFire#3]
Hello, Thanks for making this package.

I can't install it however when i'm doing install_github(repo = 'kafku/RcppFire@develop'):

i get  Error : Invalid DESCRIPTION file

Malformed maintainer field.

See the information on DESCRIPTION files in section 'Creating R
packages' of the 'Writing R Extensions' manual.

ERROR: installing package DESCRIPTION failed for package ‘RcppFire’
- removing ‘/home/ogami/R/x86_64-unknown-linux-gnu-library/3.1/RcppFire’
  Error: Command failed (1)

**Comment by kafku** [comment]
@ogamimusashi 
Thank you for your report.

This was caused by the Maintainer in DESCRIPTION file without my email address.
I will update DESCRIPTION.

**Comment by kafku** [comment]
@ogamimusashi 

I updated DESCRIPTION file.

Thank you.
